name: coverage

on: [push]

jobs:
  python-test-coverage:
    name: Python Coverage
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'


    - name: Install pip package with dependencies
      run: |
        pip install .
        pip install -r dev-requirements.txt

    - name: Run tests
      run: |
        pytest tests --cov=eclio --cov-report=xml:cov.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: cov.xml
